ToDo.Web/Models/Do/DoListingModel.cs
using System.Collections.Generic;
using System.Linq;
using ToDo.Services.Models;

namespace ToDo.Web.Models.Do
{
    public class DoListingModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public virtual IEnumerable<DoListingModel> SubTasks { get; set; }
        

        public DoListingModel(DoServiceModel model)
        {
            Id = model.Id;
            Title = model.Title;

            if (model.SubTasks != null && model.SubTasks.Any())
            {
                SubTasks = model.SubTasks.Select(s => new DoListingModel(s)).ToList();
            }
            else
            {
                SubTasks = new List<DoListingModel>();
            }
        }
    }
}

ToDo.Web/Models/Do/DoViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using ToDo.Data.Models.Static;
using ToDo.Services.Models;

namespace ToDo.Web.Models.Do
{
    public class DoListingViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public virtual List<DoListingViewModel> SubTasks { get; set; }


        public DoListingViewModel(DoServiceModel model)
        {
            Id = model.Id;
            Title = model.Title;

            if (model.SubTasks != null && model.SubTasks.Any())
            {
                SubTasks = model.SubTasks.Select(s => new DoListingViewModel(s)).ToList();
            }
            else
            {
                SubTasks = new List<DoListingViewModel>();
            }
        }
    }

    public class DoCreateViewModel
    {
        [Required(ErrorMessage = "Необходимо ввести название")]
        [StringLength(125, MinimumLength = 3, 
            ErrorMessage = "Название должно содержать не менее 3 и не более 125 символов")]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [StringLength(250, MinimumLength = 3,
            ErrorMessage = "Описание должно содержать не менее 3 и не более 250 символов")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Executors")]
        public string Executors { get; set; }

        [Range(1,60, ErrorMessage = "Планируемое время должно находиться в промежутке от 1 до 60")]
        [Display(Name = "Plan")]
        public string Plan { get; set; }
    }

    public class DoUpdateViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Необходимо ввести название")]
        [StringLength(35, MinimumLength = 3,
            ErrorMessage = "Название должно содержать не менее 3 и не более 35 символов")]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Executors")]
        public string Executors { get; set; }

        [Display(Name = "Status")]
        public DoStatus Status { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", 
            ApplyFormatInEditMode = true)]
        [Display(Name = "Done")]
        public DateTime? Done { get; set; }

        [Display(Name = "Fact")]
        public int? Fact { get; set; }

        public DoUpdateViewModel(DoServiceModel model)
        {
            Id = model.Id;
            Title = model.Title;
            Description = model.Description;
            Executors = model.Executors;
            Status = model.Status;
            Done = model.Done;
            Fact = model.Fact;
        }

        public DoUpdateViewModel()
        {

        }
    }

    public class DoDescriptionViewModel
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public DoDescriptionViewModel(DoServiceModel model)
        {
            Id = model.Id;
            Description = model.Description;
        }
    }

    public class DoDetailsViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Executors")]
        public string Executors { get; set; }

        [Display(Name = "Status")]
        public DoStatus Status { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}",
               ApplyFormatInEditMode = true)]
        [Display(Name = "Created")]
        public DateTime Created { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Done")]
        public DateTime? Done { get; set; }

        private int _plan { get; set; }

        [Display(Name = "Plan")]
        public int Plan
        {
            get
            {
                if (SubTasks != null && SubTasks.Any())
                    return _plan + SubTasks.Sum(x => x.Plan);
                else
                    return _plan;
            }

            set
            {
                _plan = value;
            }
        }

        private int? _fact { get; set; }

        [Display(Name = "Fact")]
        public int? Fact
        {
            get
            {
                if (SubTasks != null && SubTasks.Any())
                    return _fact + SubTasks.Sum(x => x.Fact);
                else
                    return _fact;
            }

            set
            {
                _fact = value;
            }
        }

        public List<DoDetailsViewModel> SubTasks { get; set; }

        public DoDetailsViewModel(DoServiceModel model)
        {
            Id = model.Id;
            Title = model.Title;
            Description = model.Description;
            Executors = model.Executors;
            Status = model.Status;
            Created = model.Created;
            Done = model.Done;
            Plan = model.Plan;
            Fact = model.Fact;

            if (model.SubTasks != null && model.SubTasks.Any())
            {
                SubTasks = model.SubTasks.Select(s => new DoDetailsViewModel(s)).ToList();
            }
            else
            {
                SubTasks = new List<DoDetailsViewModel>();
            }
        }
    }

    public class DoDeleteViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        public DoDeleteViewModel(DoServiceModel model)
        {
            Id = model.Id;
            Title = model.Title;
            Description = model.Description;
        }
    }

}

ToDo.Web/Controllers/DoController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using ToDo.Services.Infrastructure.Exceptions;
using ToDo.Services.Interfaces;
using ToDo.Services.Models;
using ToDo.Web.Infrastructure.Logger;
using ToDo.Web.Models.Do;

namespace ToDo.Web.Controllers
{
    [SkipStatusCodePages]
    public class DoController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IDoService _doService;
        private readonly IStringLocalizer<DoController> _localizer;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public DoController(
            ILoggerManager logger,
            IDoService doService,
            IStringLocalizer<DoController> localizer,
            IStringLocalizer<SharedResource> sharedLocalizer
            )
        {
            _logger = logger;
            _doService = doService;
            _localizer = localizer;
            _sharedLocalizer = sharedLocalizer;
        }

        public IActionResult Index()
        {
            var model = _doService.GetDoes()
                .Select(x => new DoListingViewModel(x));
            
            return View(model);
        }

        public ViewResult Create()
        {
            return View(new DoCreateViewModel());
        }

        [HttpPost]
        public IActionResult Create(
            [Bind("Title, Description, Executors, Plan")] DoCreateViewModel model
            )
        {
            if (ModelState.IsValid)
            {
                var newDo = new DoServiceModel
                {
                    Title = model.Title,
                    Description = model.Description,
                    Executors = model.Executors,
                    Plan = int.Parse(model.Plan)
                };

                _doService.CreateDo(newDo);

                TempData["Message"] = "Задача " + newDo.Title + " успешно создана!";

                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "Задача " + model.Title + " не может быть создана!";

            return View(model);
        }

        public ViewResult Update(int id)
        {
            var toDo = _doService.GetDo(id);

            if (toDo != null)
            {
                return View(new DoUpdateViewModel(toDo));
            }

            throw new NullReferenceException(message: "Задача не может быть изменена, так как не была найдена в БД");
        }

        [HttpPost]
        public IActionResult Update(
            [Bind("Id, Title, Description, Executors, Status, Done, Fact")] DoUpdateViewModel model
            )
        {
            if (ModelState.IsValid)
            {
                var doForUpdate = _doService.GetDo(model.Id);

                if (doForUpdate != null)
                {
                    var updatingDo = new DoServiceModel
                    {
                        Id = model.Id,
                        Title = model.Title,
                        Description = model.Description,
                        Executors = model.Executors,
                        Status = model.Status,
                        Done = model.Done,
                        Fact = model.Fact
                    };

                    _doService.UpdateDo(updatingDo);
                    
                    TempData["Message"] = "Задача " + model.Title + " успешно обновлена!";
                }

                return RedirectToAction("Index");
            }

            TempData["Message"] = "Задача " + model.Title + " не может быть обновлена";

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _doService.GetDo(id);

            if (model != null)
                return View(new DoDetailsViewModel(model));
            else
                return NotFound();
        }

        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            var toDo = _doService.GetDo(id);

            if (toDo != null)
            {
                return View(new DoDeleteViewModel(toDo));
            }

            return NotFound();
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var toDo = _doService.GetDo(id);

            if (toDo != null)
            {
                _doService.DeleteDo(toDo.Id);

                TempData["Message"] = "Задача " + toDo.Title + " была успешно удалена";

                return RedirectToAction("Index");
            }
            else
                return NotFound();
        }

        public ViewResult AddSubTask(int id)
        {
            var toDo = _doService.GetDo(id);

            ViewData["TerminalId"] = toDo.Id;
            ViewData["TerminalTitle"] = toDo.Title;
            
            return View(new DoCreateViewModel());
        }

        [HttpPost]
        public IActionResult AddSubTask(int terminalId,
            [Bind("Title, Description, Executors, Plan")] DoCreateViewModel model
            )
        {
            var terminal = _doService.GetDo(terminalId);

            if (terminal == null)
                throw new ValidationException("Терминальная задача не найдена");

            if (ModelState.IsValid)
            {
                var newDo = new DoServiceModel
                {
                    Title = model.Title,
                    Description = model.Description,
                    Executors = model.Executors,
                    Plan = int.Parse(model.Plan)
                };

                newDo = _doService.GetDo(_doService.CreateDo(newDo).Value);

                terminal.SubTasks.Add(newDo);
                _doService.UpdateDo(terminal);

                TempData["Message"] = "Подзадача " + newDo.Title + " успешно создана!";

                return RedirectToAction("Index");
            }

            TempData["Message"] = "Подзадача " + model.Title + " не может быть создана!";

            return RedirectToAction("Index");
        }

        public IActionResult ThrowException()
        {
            throw new DoSetDoneException();
        }

        public string GetCulture(string code="")
        {
            if (!String.IsNullOrEmpty(code))
            {
                CultureInfo.CurrentCulture = new CultureInfo(code);
                CultureInfo.CurrentUICulture = new CultureInfo(code);
            }

            return $"CurrentCulture: { CultureInfo.CurrentCulture.Name}, CurrentUICulture: { CultureInfo.CurrentUICulture.Name}";
            
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        public PartialViewResult GetDescription(string jsonInput)
        {
            var model = new DoDescriptionViewModel(_doService.GetDo(int.Parse(jsonInput)));

            if (model != null)
            {
                return PartialView("_DisplayTaskDescriptionPartial", model);
            }
            else
                throw new NullReferenceException();
        }
    }
}

ToDo.Web/Views/Do/AddSubTask.cshtml
@model ToDo.Web.Models.Do.DoCreateViewModel

@{
    ViewData["Title"] = "Создать подзадачу к " + ViewData["TerminalTitle"];
}

<div class="createForm">
    <form asp-antiforgery="true" asp-action="AddSubTask" method="post">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" />
            <span asp-validation-for="Description"></span>
        </div>
        <div class="form-group">
            <label asp-for="Executors"></label>
            <input asp-for="Executors" />
            <span asp-validation-for="Executors"></span>
        </div>
        <div class="form-group">
            <label asp-for="Plan"></label>
            <input asp-for="Plan" />
            <span asp-validation-for="Plan"></span>
        </div>
        <input type="hidden" name="terminalId" value="@ViewData["TerminalId"]" />
        <div class="form-group">
            <input type="submit" value="Создать" />
            <button class="back cancel" type="submit" asp-controller="Do" asp-action="Index">Назад</button>
        </div>
    </form>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
} 

ToDo.Web/Views/Do/Create.cshtml
@model ToDo.Web.Models.Do.DoCreateViewModel

@{
    ViewData["Title"] = "Создать задачу";
}

<div class="createForm">
    <form asp-antiforgery="true" asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" />
            <span asp-validation-for="Description"></span>
        </div>
        <div class="form-group">
            <label asp-for="Executors"></label>
            <input asp-for="Executors" />
            <span asp-validation-for="Executors"></span>
        </div>
        <div class="form-group">
            <label asp-for="Plan"></label>
            <input asp-for="Plan" />
            <span asp-validation-for="Plan"></span>
        </div>
        @if (ViewBag.DoId != null)
        {
            <div>
                <input type="hidden" value="ViewBag.DoId" />
            </div>
        }
        <div class="form-group">
            <input type="submit" value="Создать" />
            <button class="back cancel" type="submit" asp-controller="Do" asp-action="Index">Назад</button>
        </div>
    </form>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
} 

ToDo.Web/Views/Do/Delete.cshtml
@model ToDo.Web.Models.Do.DoDeleteViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@using System.Text
 
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = "Удалить задачу " + Model.Title;
    var sb = new StringBuilder();
}

<h1 class="warning">@sb.Append(Localizer["Warning"].Value + Model.Title + "?")</h1>

<div class="detailsForm">
    <form asp-antiforgery="true" asp-action="Delete" method="post">
        @Html.HiddenFor(m => m.Id)
        <div class="form-group">
            @Html.DisplayNameFor(m => m.Title)
            @Html.DisplayFor(m => m.Title)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(m => m.Description)
            @Html.DisplayFor(m => m.Description)
        </div>
        <div class="form-group">
            <input type="submit" value="Удалить" style="background-color: red;" onmouseover="this.style.backgroundColor='#FA8072'" onmouseout="this.style.backgroundColor='red'" />
            <button class="back" type="submit" asp-controller="Do" asp-action="Index">Назад</button>
        </div>
    </form>
</div>

ToDo.Web/Views/Do/Details.cshtml
@model ToDo.Web.Models.Do.DoDetailsViewModel

@{ 
    ViewData["Title"] = "Информация о задаче " + Model.Title;
}

    <div class="detailsForm">
        <form>
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                @Html.LabelFor(m => m.Title)
                @Html.DisplayFor(m => m.Title)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Description)

                @if (Model.Description != null)
                {
                    @Html.DisplayFor(m => m.Description)
                }
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Status)
                @Html.DisplayFor(m => m.Status)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Executors)

                @if (Model.Executors != null)
                {
                    @Html.DisplayFor(m => m.Executors)
                }
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Created) 
                @Html.DisplayFor(m => m.Created)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Done)

                @if (Model.Done != null)
                {
                    @Html.DisplayFor(m => m.Done)
                }
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Plan)
                @Html.DisplayFor(m => m.Plan)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Fact)

                @if (Model.Fact != default(int))
                {
                    @Html.DisplayFor(m => m.Fact)
                }
            </div>

            @if (Model.SubTasks.Any())
            {
                <div class="form-group">
                <p>Лист подзадач:</p>
                @foreach (var sub in Model.SubTasks)
                {
                    <div class="subTask">@sub.Title - Запланированное полное время выполнения: @sub.Plan</div>
                }
                </div>
            }
            <button class="back" type="submit" asp-controller="Do" asp-action="Index">Назад</button>
        </form>
    </div>

ToDo.Web/Views/Do/Index.cshtml
@model IEnumerable<ToDo.Web.Models.Do.DoListingViewModel>

@{
    ViewData["Title"] = "Главная";
}

<div id="content">
    <div class="column side">
        @await Html.PartialAsync("_DisplayTasksPartial")
    </div>
    <div class="column middle"></div>
</div>

ToDo.Web/Views/Do/Update.cshtml
@model ToDo.Web.Models.Do.DoUpdateViewModel
@using ToDo.Web.Helpers

@{
    ViewData["Title"] = "Редактирование " + Model.Title;
}

<div class="updateForm">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Id)
        <div class="form-group">
            @Html.LabelFor(m => m.Title)
            @Html.EditorFor(m => m.Title)
            @Html.ValidationMessageFor(m => m.Title)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description)
            @Html.EditorFor(m => m.Description)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Executors)
            @Html.EditorFor(m => m.Executors)
        </div>
        <div class="form-group select">
            @Html.LabelFor(m => m.Status)
            <select asp-for="Status"
                    asp-items="Html.updateModelSelectListItem(Model)">
            </select>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Done)
            @Html.EditorFor(m => m.Done)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Fact)
            @Html.EditorFor(m => m.Fact)
        </div>
        <div class="form-group">
            <input type="submit" value="Сохранить" />
            <button class="back cancel" type="submit" asp-controller="Do" asp-action="Index">Назад</button>
        </div>
    }
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

ToDo.Web/Views/Do/_DisplaySubTasksPartial.cshtml
@model IEnumerable<ToDo.Web.Models.Do.DoListingViewModel>

    <ul class="toDoItems nested">
        @foreach (var item in Model)
        {
            <li class="toDoItem">
            <input class="toDoItemId" type="hidden" value="@item.Id" />
            @if (item.SubTasks.Count() > 0)
            {
                <i class="toDoArrow"></i>
                <span class="toDoItemTitle">@item.Title</span>
                @await Html.PartialAsync("_DisplaySubTasksPartial", item.SubTasks)
            }
            else
            {
                <span class="toDoItemTitle noSubTasks">@item.Title</span>
            }
            </li>
        }
    </ul>

ToDo.Web/Views/Do/_DisplayTaskDescriptionPartial.cshtml
@model ToDo.Web.Models.Do.DoDescriptionViewModel

    <p class="toDoItemDescription">@Model.Description</p>
    <div class="buttons">
        <a class="details" asp-controller="Do" asp-action="Details" asp-route-id="@Model.Id">Подробнее</a>
        <a class="update" asp-controller="Do" asp-action="Update" asp-route-id="@Model.Id">Изменить</a>
        <a class="delete" asp-controller="Do" asp-action="Delete" asp-route-id="@Model.Id">Удалить</a>
        <a class="addSubTask" asp-controller="Do" asp-action="AddSubTask" asp-route-id="@Model.Id">Добавить подзадачу</a>
    </div>

ToDo.Web/Views/Do/_DisplayTasksPartial.cshtml
@model IEnumerable<ToDo.Web.Models.Do.DoListingViewModel>


    <ul class="toDoItems">
        @foreach (var item in Model)
        {

            <li class="toDoItem">
            <input class="toDoItemId" type="hidden" value="@item.Id" />
            @if (item.SubTasks.Count() > 0)
            {
                <i class="toDoArrow"></i>
                <span class="toDoItemTitle">@item.Title</span>
                @await Html.PartialAsync("_DisplaySubTasksPartial", item.SubTasks)
            }
            else
            {
                <span class="toDoItemTitle noSubTasks">@item.Title</span>
            }
            </li>
        }
    </ul>